name: Create Place Light Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  validate_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Validate Action to do the deserialize
        uses: ./actions/validate

      - name: List dist contents for debugging
        run: |
          echo "Contents of ./dist:"
          ls -lR ./dist

      # Extract version from the tag
      - name: Extract version from tag
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
     
      - name: Get current  FOMOD version
        id: fomod_version
        run: | 
          echo "FOMOD_VERSION=$(xmlstarlet sel -t -m '//Version' -v . ./package/fomod/info.xml)" >> $GITHUB_OUTPUT


      - name: Update FOMOD XML with version
        if: ${{ steps.fomod_version.outputs.FOMOD_VERSION !=  steps.extract_version.outputs.VERSION }}
        run: | 
          xmlstarlet ed --inplace -u '//Version' -v "${{ steps.extract_version.outputs.VERSION }}" ./package/fomod/info.xml
          cp ./package/fomod/info.xml ./dist/fomod/info.xml
          cat ./dist/fomod/info.xml

      # Archive dist directory
      - name: Archive dist directory
        run: |          
          cd ./dist ; zip -r ../downloads/PlacedLight.zip *

      # Upload artifact
      - name: Upload artifact
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ steps.extract_version.outputs.VERSION }} ./downloads/PlacedLight.zip
