name: Create Place Light Package

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  validate_and_publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Choco install xmlstarlet
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install xmlstarlet

      # Same as Validate - not sure how to just call Validate
      - name: Validate json
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: https://raw.githubusercontent.com/FlayaN/LightPlacer-VR/refs/heads/json-schema/schema.json
          file: package/**/LightPlacer/**/*.json
            
      - name: Download release archive
        uses: robinraju/release-downloader@v1
        with:
          repository: 'Mutagen-Modding/Spriggit'
          latest: true
          zipBall: true
          fileName: 'SpriggitCLI.zip'
          out-file-path: './downloads'
      
      - name: Extract archive
        run: unzip ./downloads/SpriggitCLI.zip -d ./SpriggitCLI

      # Extract version from the tag
      - name: Extract version from tag
        id: version_extraction
        run: |
          if ($env:GITHUB_REF -match '\d+\.\d+\.\d+') {
            $versionTag = $matches[0]
            echo "::set-output name=VERSION_TAG::$versionTag"
          } else {
            Write-Error "No valid version found in GITHUB_REF: $env:GITHUB_REF"
          }
        shell: pwsh   

      - name: Show TAG Version
        run: | 
          Write-Host "VERSION_TAG=$env:VERSION_TAG"
        shell: pwsh
      
      - name: Run Spriggit main deserialization
        run: ./deserialize.bat
        shell: cmd
 
      - name: Get current FOMOD version
        id: fomod_version
        run: | 
          echo "::set-output name=FOMOD_VERSION::$(xml sel -t -m '//Version' -v . ./dist/fomod/info.xml)"

      - name: Show FOMOD Version
        run: | 
          Write-Host "FOMOD_VERSION=$env:FOMOD_VERSION"
        shell: pwsh
           
      - name: Update FOMOD XML with version
        if: ${{ steps.fomod_version.outputs.FOMOD_VERSION != steps.version_extraction.outputs.VERSION_TAG }}
        run: | 
          xml ed --inplace -u '//Version' -v "${{ steps.version_extraction.outputs.VERSION_TAG }}" ./dist/fomod/info.xml
          type ./dist/fomod/info.xml
           
      # Archive dist directory
      - name: Archive dist directory
        run: |          
          cd ./dist ; tar --format zip -cf ..\downloads\PlacedLight.zip *

      # Upload artifact
      - name: Upload artifact
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{github.event.release.tag_name}} ./downloads/PlacedLight.zip
